# Generated by Django 5.0.3 on 2024-03-12 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название отдела')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.TextField(blank=True, verbose_name='Название книги')),
                ('author', models.TextField(blank=True, verbose_name='Автор книги')),
                ('time_publication', models.DateTimeField(verbose_name='Дата публикации')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во экземпляров')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksite.dept')),
            ],
        ),
        migrations.CreateModel(
            name='BookBorrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksite.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booksite.user')),
            ],
        ),
    ]
